# -*- coding: utf-8 -*-
"""Tarea1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8RxEGXYWTYN3bgD3WRVutMu4Rl7uYpv

📘  Ejercicio 1: Calcular el número mayor de una lista sin usar
max
 Cree un programa que reciba una lista de números y devuelva el número mayor sin usar la función
 max()
 .
 # Entrada: [3, 9, 4, 1, 15]
 # Salida esperada: 15
"""

entrada =[3,20,8,1,55]
i=0
numeroMayor=0
while i<len(entrada):
  if(numeroMayor<entrada[i]):
    numeroMayor=entrada[i]

  i+=1

print(numeroMayor)

"""📘  Ejercicio 2: Escriba un programa que solicite un número al usuario y
 muestre la tabla de multiplicar del 1 al 10 de ese número.

  #### Entrada: 3
  Salida esperada:
*  3 x 1 = 3
* 3 x 2 = 6
*  ...
* 3 x 10 = 30
"""

numero = int(input("Ingresa numero"))

for i in range (0,11):
  print(f"{numero} x {i} = {numero*i}")

"""📘 Ejercicio 3: Cree un programa que elimine los elementos repetidos de una
 lista y devuelva una nueva lista con elementos únicos ordenados.
"""

lista = [5, 8, 3, 5, 2, 8, 9, 1, 3, 4, 5, 9, 7, 2, 6, 8]
miListaSinDuplicados=[]
vistos=set()

for numero in lista:
  if miListaSinDuplicados not in vistos:
    miListaSinDuplicados.append(numero)
    vistos.add(numero)

print(miListaSinDuplicados)

"""📘  Ejercicio 4: Escriba un programa que solicite ingresar el nombre de varios
 estudiantes y su nota, y lo almacene en un diccionario. Al final, muestra los
 datos almacenados.
"""

dicionario={}
bandera=True

while bandera:
  clave=input("Nombre")
  valor=int(input("Nota"))
  continuar=input("Continuar S / N: ")
  dicionario[clave]=valor
  if continuar.capitalize()!="S":
    bandera=False

print(dicionario)

"""
📘  Ejercicio 5: Sumar ventas por producto
 Dado el siguiente diccionario:

 ventas = {
 'Producto': ['A', 'B', 'A', 'C', 'B', 'A'],
 'Cantidad': [10, 5, 7, 3, 2, 8]
 }
 Agrupa las cantidades por producto y muestra la suma total de ventas por cada uno.
 # Salida esperada:
 # {'A': 25, 'B': 7, 'C': 3}"""

ventas = {
 'Producto': ['A', 'B', 'A', 'C', 'B', 'A'],
 'Cantidad': [10, 5, 7, 3, 2, 8]
 }

#variable para almacenar ventas
ventasTotales={}

#  RELACIONAR CADA INDICE DE CADA CLAVE
for i in range(len(ventas['Producto'])):
  producto=ventas['Producto'][i]
  cantidad=ventas['Cantidad'][i]

  #validar que el producto ya ente en mi dicionrio caso que no este se agrega
  if producto in ventasTotales:
    ventasTotales[producto]+=cantidad
  else:
    ventasTotales[producto]=cantidad

print(ventasTotales)